Document: bloonix-plugins-pgsql
Title: Debian bloonix-plugins-pgsql Manual
Author: <insert document author here>
Abstract: This manual describes what bloonix-plugins-pgsql is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bloonix-plugins-pgsql/bloonix-plugins-pgsql.sgml.gz

Format: postscript
Files: /usr/share/doc/bloonix-plugins-pgsql/bloonix-plugins-pgsql.ps.gz

Format: text
Files: /usr/share/doc/bloonix-plugins-pgsql/bloonix-plugins-pgsql.text.gz

Format: HTML
Index: /usr/share/doc/bloonix-plugins-pgsql/html/index.html
Files: /usr/share/doc/bloonix-plugins-pgsql/html/*.html


